{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinyraven.fullname" . }}
  labels:
    {{- include "tinyraven.labels" . | nindent 4 }}
type: Opaque
stringData:
  TR_ADMIN_TOKEN: {{ .Values.adminToken | quote }}
  TR_CLICKHOUSE_PASSWORD: {{ .Values.env.clickhouse.password | quote }}
{{- end }}
